<?php

	echo $this->tableform_helper()->tableForm($this->object,$this->listitems)
									->setAttributes(array('class'=>'table_all_form'))
	
				->setPrefix($this->prefix)
				
				->setColumnSortByName('Id')  
  				->setColumnSearchByName('Title','Name Intro:En')
  				->setColumnSearchByName('Createdby','Created By:Displayname')
  				->setColumnDateTimeByName('Date Time Updated:Updated')
  				->setColumnDateByName('Date Created:Created')
  				
  				->setStatus('News')
  				->setPriority()
  				 
  				->setActionEdit($this->url('admin',array('controller'=>'page','action'=>'detail')))
	  			->setActionDelete('/include/delete/name/pages')
				
				->toString();
	
	echo $this->paginator_helper()->paginator($this->paginator);
?>