<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <?php echo $this->headTitle('Zend Frame WORK 2 + Doctrine');?>

    <?php $this->headMeta()->appendName('robots', 'index, follow'); ?>
    <?php echo $this->headMeta()->appendName('description', 'zend2 test'); ?>
    <?php echo $this->headMeta()->appendName('keywords', 'zend2, doctrine2, framework, mvc module'); ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/application/favicon.ico'))
				    ->prependStylesheet($this->basePath(). '/css/application/main.css');
				    //->prependStylesheet($this->basePath(). '/css/ui-lightness/jquery-ui-1.9.0.custom.min.css');
	?>

    <!-- Scripts -->
    <?php echo $this->headScript()//->prependFile($this->basePath() . '/js/jquery-ui-1.9.0.custom.min.js')
                                  ->prependFile($this->basePath() . '/js/jquery-1.8.2.min.js')                                  
    							  ->appendFile($this->basePath() . '/js/jstween-1.1.min.js') 
    							  ->appendFile($this->basePath() . '/js/application/main.js') ?>
  </head>

  <body>
  	<div id="container">
  		<?php echo $this->content; ?>
  	</div>
  </body>
</html>
