<?php
// module/Album/view/album/album/add.phtml:

$title = 'Đổi mật khẩu tài khoản quản trị';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('index', array('action' => 'change-password')));
$form->prepare();

echo $this->form()->openTag($form);
echo '<table>';
echo '<tr><td>Mật khẩu hiện tại</td><td>'.$this->formRow($form->get('current')).'</td></tr>';
echo '<tr><td>Mật khẩu mới</td><td>'.$this->formRow($form->get('new')).'</td></tr>';
echo '<tr><td>Xác nhận mật khẩu mới</td><td>'.$this->formRow($form->get('confirm')).'</td></tr>';
echo '<tr><td colspan=\'2\'><input type=\'submit\' id=\'submitbutton\' value=\'Đăng nhập\'/></td></tr>';
echo '</table>';
echo $this->form()->closeTag();
